"""add course prerequisites

Revision ID: 058a3bcabf14
Revises: 88093e086c0d
Create Date: 2026-08-20 16:46:36.650769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058a3bcabf14'
down_revision: Union[str, Sequence[str], None] = '88093e086c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('required_code', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'required_code', 'kind')
    )
    # The PK covers "what does X require". This serves the reverse direction --
    # "what unlocks X" -- which is how leadingTo is derived instead of stored.
    op.create_index('ix_prereq_reverse', 'course_prerequisites',
                    ['required_code', 'kind'])
    op.add_column('courses', sa.Column('prerequisites_text', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('corequisites_text', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('restrictions_text', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('logical_prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('courses', sa.Column('logical_corequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'logical_corequisites')
    op.drop_column('courses', 'logical_prerequisites')
    op.drop_column('courses', 'restrictions_text')
    op.drop_column('courses', 'corequisites_text')
    op.drop_column('courses', 'prerequisites_text')
    op.drop_index('ix_prereq_reverse', table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    # ### end Alembic commands ###
