"""create courses, sections, seat_observations

Revision ID: 4560584efa04
Revises: 
Create Date: 2026-08-13 14:28:24.406296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4560584efa04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('catalogue_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('crn', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('instructor', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('section_no', sa.String(), nullable=True),
    sa.Column('type_of_class', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('crn')
    )
    op.create_table('seat_watch',
    sa.Column('crn', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_seats', sa.Integer(), nullable=True),
    sa.Column('waitlist_count', sa.Integer(), nullable=True),
    sa.Column('waitlist_seats', sa.Integer(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('max_enrol', sa.Integer(), nullable=True),
    sa.Column('non_reserved', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crn'], ['sections.crn'], ),
    sa.PrimaryKeyConstraint('crn', 'observed_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_watch')
    op.drop_table('sections')
    op.drop_table('courses')
    # ### end Alembic commands ###
