"""...

Revision ID: b2841debb69e
Revises: 4560584efa04
Create Date: 2026-08-17 13:59:36.711465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2841debb69e'
down_revision: Union[str, Sequence[str], None] = '4560584efa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_instructors',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'term', 'name')
    )
    op.add_column('courses', sa.Column('credits_text', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('credits_min', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('courses', sa.Column('credits_max', sa.Numeric(precision=4, scale=2), nullable=True))
    op.drop_column('courses', 'credits')
    op.add_column('sections', sa.Column('meetings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('sections', 'instructor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('instructor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sections', 'meetings')
    op.add_column('courses', sa.Column('credits', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True))
    op.drop_column('courses', 'credits_max')
    op.drop_column('courses', 'credits_min')
    op.drop_column('courses', 'credits_text')
    op.drop_table('course_instructors')
    # ### end Alembic commands ###
